dataset:
    root_dir: '/home/jiatian/dataset/nyu/'
    image_height: 240
    image_width: 320
    min_depth: 0.1
    max_depth: 20.
    preprocess: False
model:
    root_dir: '/home/jiatian/project/tf-monodepth2/saved_model_nyu/'
    learning_rate: 1e-4
    batch_size: 8
    num_source: 3
    num_scales: 4
    epoch: 40
    beta1: 0.9
    reproj_alpha: 0.85
    smooth_alpha: 1e-3
    batch_norm_decay: 0.95
    batch_norm_epsilon: 1e-5
    pose_scale: 1e-2
    auto_mask: True
    #continue_ckpt: ''
    continue_ckpt: '/home/jiatian/project/tf-monodepth2/saved_model_tum/quantize_friendly/model-3257210'
    torch_res18_ckpt: ''
    #torch_res18_ckpt: '/home/jiatian/project/tf-monodepth2/res_model_extractor/resnet18.npy'
    summary_freq: 200
    pose_type: 'seperate' # seperate or shared
