dataset:
    root_dir: '/home/jiatian/dataset/nyu/'
    image_height: 480
    image_width: 640
    min_depth: 0.1
    max_depth: 10.
    preprocess: True
model:
    root_dir: '/home/jiatian/project/tf-monodepth2/saved_model/ckpt_nod/'
    learning_rate: 1e-4
    batch_size: 8
    num_source: 3
    num_scales: 4
    epoch: 40
    beta1: 0.9
    reproj_alpha: 0.85
    smooth_alpha: 1e-2
    batch_norm_decay: 0.95
    batch_norm_epsilon: 1e-5
    pose_scale: 1e-2
    auto_mask: True
    #continue_ckpt: ''
    continue_ckpt: '/home/jiatian/project/tf-monodepth2/saved_model/ckpt_nod/0212_224_160/model.latest'
    #torch_res18_ckpt: ''
    torch_res18_ckpt: '/home/jiatian/project/tf-monodepth2/res_model_extractor/resnet18.npy'
    summary_freq: 200
    pose_type: 'seperate' # seperate or shared
