dataset:
    root_dir: '/home/nod/datasets/robot/20200611/train_supervise/'
    image_height: 480
    image_width: 640
    min_depth: 0.1
    max_depth: 10.
    preprocess: True
model:
    root_dir: '/home/nod/project/tf-monodepth2/saved_model/'
    learning_rate: 1e-2
    batch_size: 8
    epoch: 80
    beta1: 0.9
    reproj_alpha: 0.85
    smooth_alpha: 1e-1
    batch_norm_decay: 0.95
    batch_norm_epsilon: 1e-5
    pose_scale: 1e-2
    auto_mask: True
    #continue_ckpt: ''
    continue_ckpt: 'saved_model/ckpt_640_480/model-756002'
    #torch_res18_ckpt: ''
    torch_res18_ckpt: '/home/nod/project/tf-monodepth2/res_model_extractor/resnet18.npy'
    summary_freq: 2
    pose_type: 'seperate' # seperate or shared
    pb_path: '/home/nod/project/tf-monodepth2/saved_model/ckpt_640_480_finetune/0615/saved_model.pb'
    inference_ckpt: True
